---

- name: Download consul-template binary
  unarchive:
    src: "{{ cons_template_dwn_url }}"
    dest: /usr/local/bin
    remote_src: yes
  tags: consul-template

#- name: Copy template file
#  template:
#    src: pgbouncer.ini.template.j2
#    dest: /etc/pgbouncer/pgbouncer.ini.template
#    owner: postgres
#    group: postgres
#    mode: 0664
#  tags: consul-template

- name: Creates directory
  file:
    path: /etc/consul-template.d
    state: directory

- name: Copy templates
  copy:
    src: "{{ item }}"
    dest: "/etc/consul-template.d/{{ item }}"
    owner: root
    group: root
    mode: 0660
  with_items:
    - pki-demo.hcl
    - yet-cert.tpl
    - yet-key.tpl
  tags: consul-template

- name: Copy systemd unit file
  template:
    src: consul-template.service.j2
    dest: /etc/systemd/system/consul-template.service
    owner: root
    group: root
    mode: 0660
  tags: consul-template

- name: Reload daemon
  systemd:
    daemon_reload: yes
  tags: consul-template

- name: Start and enable consul-template
  service:
    name: consul-template
    state: restarted
    enabled: yes
  tags: consul-template

